# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cnidofest
email: cnidofest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Cnidarian Model Systems Meeting
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cnidofest.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cnidofest
github_username:  matthewnicotra

# Build settings
remote_theme: matthewnicotra/hydejack-matthewnicotra
plugins:
  - jekyll-feed
  - jekyll-include-cache


# Hydejack specific formatting for the sidebar menue
menu:

  - title: "Cnidofest 2022"
    url:   /cnidofest-2022/
  - title: "Zoom Seminars"
    url: /zoom-seminars/
  - title: "Past Meetings"
    url: /past-meetings/
  #- title: Blog
  #  url: /blog/
  - title: About
    url: /about/


# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2021. All rights reserved.

# This will appear in the sidebar
#logo: /assets/images/whatever.jpg

favicon: /fdfavicon.ico






# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# small edit
